import React, { useCallback, useRef, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { toast } from 'react-toastify';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import VastuScoreCard from './VastuScoreCard';
import FloorPlanSummary from './FloorPlanSummary';
import VastuWarningsBanner from './VastuWarningsBanner';

const VastuReport = ({ result, onReset }) => {
    const reportRef = useRef(null);
    const [isDownloading, setIsDownloading] = useState(false);

    // Get markdown from the correct location (top level, not inside data)
    const reportMarkdown = result?.report_markdown || '';

    const handleCopy = useCallback(async () => {
        try {
            await navigator.clipboard.writeText(reportMarkdown);
            toast.success('Report copied to clipboard!', {
                position: 'bottom-right',
                autoClose: 3000
            });
        } catch {
            toast.error('Failed to copy. Please try selecting and copying manually.', {
                position: 'bottom-right'
            });
        }
    }, [reportMarkdown]);

    const handlePrint = useCallback(() => {
        const printContent = reportRef.current?.innerHTML || '';
        const printWindow = window.open('', '_blank');
        if (printWindow) {
            printWindow.document.write(`
                <!DOCTYPE html>
                <html>
                <head>
                    <title>Vastu Analysis Report - 360Ghar</title>
                    <style>
                        body {
                            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                            line-height: 1.6;
                            padding: 40px;
                            max-width: 800px;
                            margin: 0 auto;
                            color: #333;
                        }
                        h1 { color: #F05A22; border-bottom: 2px solid #F69220; padding-bottom: 10px; }
                        h2 { color: #333; margin-top: 30px; }
                        h3 { color: #555; }
                        h4 { color: #666; }
                        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
                        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                        th { background-color: #FFF5EB; color: #F05A22; }
                        tr:nth-child(even) { background-color: #f9f9f9; }
                        .score-section {
                            background: linear-gradient(135deg, #FFF5EB 0%, #FFE4CC 100%);
                            padding: 30px;
                            border-radius: 12px;
                            margin: 20px 0;
                            text-align: center;
                            border: 1px solid #F69220;
                        }
                        .score-number { font-size: 56px; font-weight: bold; color: #F05A22; }
                        .score-label { font-size: 18px; color: #666; margin-top: 5px; }
                        ul, ol { margin-left: 20px; }
                        li { margin-bottom: 8px; }
                        .disclaimer {
                            background: #f8f9fa;
                            padding: 15px;
                            border-radius: 8px;
                            margin-top: 30px;
                            font-size: 12px;
                            color: #666;
                            border-left: 3px solid #F69220;
                        }
                        @media print {
                            body { padding: 20px; }
                            .no-print { display: none; }
                        }
                    </style>
                </head>
                <body>
                    <div class="score-section">
                        <div class="score-number">${result.data?.vastu_score || 'N/A'}/10</div>
                        <div class="score-label">Vastu Compliance Score</div>
                    </div>
                    ${printContent}
                    <div class="disclaimer">
                        <strong>Disclaimer:</strong> ${result.data?.disclaimer || 'This analysis is based on traditional Vastu Shastra principles and should be considered alongside modern architectural requirements.'}
                    </div>
                    <footer style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #F69220; color: #666; font-size: 12px; text-align: center;">
                        <img src="https://360ghar.com/assets/images/logo.png" alt="360Ghar" style="height: 30px; margin-bottom: 10px;" />
                        <div>Generated by 360Ghar Vastu Checker | www.360ghar.com</div>
                    </footer>
                </body>
                </html>
            `);
            printWindow.document.close();
            printWindow.print();
        }
    }, [result]);

    const handleDownloadPDF = useCallback(async () => {
        if (!reportRef.current) return;

        setIsDownloading(true);
        toast.info('Generating PDF...', {
            position: 'bottom-right',
            autoClose: 2000
        });

        try {
            // Create a clone to modify for PDF
            const element = reportRef.current;

            const canvas = await html2canvas(element, {
                scale: 2,
                useCORS: true,
                logging: false,
                backgroundColor: '#ffffff'
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4'
            });

            const imgWidth = 210; // A4 width in mm
            const pageHeight = 297; // A4 height in mm
            const imgHeight = (canvas.height * imgWidth) / canvas.width;
            let heightLeft = imgHeight;
            let position = 0;

            // Add first page
            pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
            heightLeft -= pageHeight;

            // Add more pages if needed
            while (heightLeft > 0) {
                position = heightLeft - imgHeight;
                pdf.addPage();
                pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
                heightLeft -= pageHeight;
            }

            // Add footer to last page
            const pageCount = pdf.internal.getNumberOfPages();
            pdf.setPage(pageCount);
            pdf.setFontSize(8);
            pdf.setTextColor(128);
            pdf.text(
                'Generated by 360Ghar Vastu Checker | www.360ghar.com',
                105,
                290,
                { align: 'center' }
            );

            pdf.save('vastu-analysis-report.pdf');

            toast.success('PDF downloaded successfully!', {
                position: 'bottom-right',
                autoClose: 3000
            });
        } catch (error) {
            console.error('PDF generation error:', error);
            toast.error('Failed to generate PDF. Please try printing instead.', {
                position: 'bottom-right'
            });
        } finally {
            setIsDownloading(false);
        }
    }, []);

    if (!result || !result.data) {
        return null;
    }

    const { data } = result;
    const hasWarnings = result.has_warnings || (data.warnings && data.warnings.length > 0);
    const criticalWarnings = result.critical_warnings ||
        data.warnings?.some(w => w.severity === 'critical');

    return (
        <div className="vastu-report">
            {/* Warnings Banner - Show before score if there are issues */}
            {hasWarnings && (
                <VastuWarningsBanner
                    warnings={data.warnings}
                    confidence={data.analysis_confidence}
                    isValidFloorPlan={data.is_valid_floor_plan}
                    onUploadNew={onReset}
                />
            )}

            {/* Score Card */}
            <VastuScoreCard
                score={data.vastu_score}
                summary={data.score_explanation}
                confidence={data.analysis_confidence}
                hasWarnings={criticalWarnings}
            />

            {/* Action Buttons */}
            <div className="report-actions d-flex justify-content-center gap-3 mb-4 flex-wrap">
                <button className="btn btn-outline-main" onClick={handleCopy}>
                    <i className="fas fa-copy me-2"></i>
                    Copy Report
                </button>
                <button className="btn btn-outline-main" onClick={handlePrint}>
                    <i className="fas fa-print me-2"></i>
                    Print Report
                </button>
                <button
                    className="btn btn-outline-main"
                    onClick={handleDownloadPDF}
                    disabled={isDownloading}
                >
                    <i className={`fas ${isDownloading ? 'fa-spinner fa-spin' : 'fa-file-pdf'} me-2`}></i>
                    {isDownloading ? 'Generating...' : 'Download PDF'}
                </button>
                <button className="btn btn-main" onClick={onReset}>
                    <i className="fas fa-redo me-2"></i>
                    Analyze Another
                </button>
            </div>

            {/* Floor Plan Summary */}
            {data.floor_plan_analysis && (
                <FloorPlanSummary floorPlanAnalysis={data.floor_plan_analysis} />
            )}

            {/* Room Analysis Summary */}
            {data.room_analysis && data.room_analysis.length > 0 && (
                <div className="room-analysis-summary bg-white p-4 rounded-3 shadow-sm mb-4">
                    <h4 className="mb-3">
                        <i className="fas fa-door-open me-2 text-main"></i>
                        Room Analysis
                    </h4>
                    <div className="row g-3">
                        {data.room_analysis.map((room, index) => (
                            <div key={index} className="col-md-6 col-lg-4">
                                <div className={`room-card p-3 rounded-2 border ${getStatusClass(room.status)}`}>
                                    <div className="d-flex justify-content-between align-items-start mb-2">
                                        <div>
                                            <h6 className="mb-1">{room.room}</h6>
                                            <small className="text-muted">{room.direction}</small>
                                        </div>
                                        <span className={`badge ${getStatusBadgeClass(room.status)}`}>
                                            {formatStatus(room.status)}
                                        </span>
                                    </div>
                                    {room.analysis && (
                                        <p className="small text-muted mb-0 mt-2">
                                            {room.analysis}
                                        </p>
                                    )}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Major Defects */}
            {data.major_defects && data.major_defects.length > 0 && (
                <div className="defects-summary bg-white p-4 rounded-3 shadow-sm mb-4">
                    <h4 className="mb-3">
                        <i className="fas fa-exclamation-triangle me-2 text-warning"></i>
                        Major Defects Identified
                    </h4>
                    <div className="defects-list">
                        {data.major_defects.map((defect, index) => (
                            <div key={index} className={`defect-item p-3 mb-2 rounded-2 ${getSeverityClass(defect.severity)}`}>
                                <div className="d-flex justify-content-between align-items-start">
                                    <div>
                                        <h6 className="mb-1">{defect.issue}</h6>
                                        <p className="text-muted mb-0 small">{defect.impact}</p>
                                    </div>
                                    <span className={`badge ${getSeverityBadgeClass(defect.severity)}`}>
                                        {defect.severity}
                                    </span>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Remedies */}
            {data.remedies && data.remedies.length > 0 && (
                <div className="remedies-summary bg-white p-4 rounded-3 shadow-sm mb-4">
                    <h4 className="mb-3">
                        <i className="fas fa-tools me-2 text-success"></i>
                        Recommended Remedies
                    </h4>
                    <div className="remedies-list">
                        {data.remedies.map((remedy, index) => (
                            <div key={index} className="remedy-item p-3 mb-2 rounded-2 bg-light">
                                <div className="d-flex align-items-start">
                                    <span className={`badge me-3 ${getRemedyTypeBadgeClass(remedy.type)}`}>
                                        {formatRemedyType(remedy.type)}
                                    </span>
                                    <div>
                                        <h6 className="mb-1">
                                            <i className="fas fa-wrench me-1 text-muted small"></i>
                                            {remedy.problem}
                                        </h6>
                                        <p className="text-muted mb-0 small">{remedy.solution}</p>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Improvements */}
            {data.improvements && data.improvements.length > 0 && (
                <div className="improvements-section bg-white p-4 rounded-3 shadow-sm mb-4">
                    <h4 className="mb-3">
                        <i className="fas fa-lightbulb me-2 text-warning"></i>
                        Suggested Improvements
                    </h4>
                    <ul className="improvements-list mb-0">
                        {data.improvements.map((improvement, index) => (
                            <li key={index} className="mb-2">
                                <i className="fas fa-check-circle text-success me-2"></i>
                                {improvement}
                            </li>
                        ))}
                    </ul>
                </div>
            )}

            {/* Full Markdown Report */}
            <div className="full-report bg-white p-4 rounded-3 shadow-sm mb-4">
                <h4 className="mb-3">
                    <i className="fas fa-file-alt me-2 text-main"></i>
                    Full Analysis Report
                </h4>
                <div ref={reportRef} className="markdown-content">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>
                        {reportMarkdown}
                    </ReactMarkdown>
                </div>
            </div>

            {/* Disclaimer */}
            {data.disclaimer && (
                <div className="disclaimer-section bg-light p-3 rounded-2 border-start border-warning border-3">
                    <small className="text-muted">
                        <i className="fas fa-info-circle me-2"></i>
                        <strong>Disclaimer:</strong> {data.disclaimer}
                    </small>
                </div>
            )}
        </div>
    );
};

// Helper functions
function getStatusClass(status) {
    switch (status?.toLowerCase()) {
        case 'good':
        case 'excellent':
            return 'border-success';
        case 'acceptable':
        case 'neutral':
            return 'border-warning';
        case 'bad':
        case 'poor':
        case 'problematic':
            return 'border-danger';
        default:
            return 'border-secondary';
    }
}

function getStatusBadgeClass(status) {
    switch (status?.toLowerCase()) {
        case 'good':
        case 'excellent':
            return 'bg-success';
        case 'acceptable':
        case 'neutral':
            return 'bg-warning text-dark';
        case 'bad':
        case 'poor':
        case 'problematic':
            return 'bg-danger';
        default:
            return 'bg-secondary';
    }
}

function formatStatus(status) {
    if (!status) return 'Unknown';
    return status.charAt(0).toUpperCase() + status.slice(1).toLowerCase();
}

function getSeverityClass(severity) {
    switch (severity?.toLowerCase()) {
        case 'high':
        case 'critical':
            return 'bg-danger-subtle';
        case 'medium':
            return 'bg-warning-subtle';
        case 'low':
            return 'bg-info-subtle';
        default:
            return 'bg-light';
    }
}

function getSeverityBadgeClass(severity) {
    switch (severity?.toLowerCase()) {
        case 'high':
        case 'critical':
            return 'bg-danger';
        case 'medium':
            return 'bg-warning text-dark';
        case 'low':
            return 'bg-info';
        default:
            return 'bg-secondary';
    }
}

function getRemedyTypeBadgeClass(type) {
    switch (type?.toLowerCase()) {
        case 'structural':
            return 'bg-primary';
        case 'placement':
            return 'bg-info';
        case 'symbolic':
            return 'bg-success';
        case 'color':
            return 'bg-warning text-dark';
        case 'element':
            return 'bg-secondary';
        default:
            return 'bg-secondary';
    }
}

function formatRemedyType(type) {
    if (!type) return 'General';
    // Handle types like "Placement|Element"
    if (type.includes('|')) {
        return type.split('|').map(t => t.trim()).join(' / ');
    }
    return type.charAt(0).toUpperCase() + type.slice(1).toLowerCase();
}

export default VastuReport;
